### ISSUE TITLE
Add `primaryAccountable` field to EconomicResource and `inventoriedEconomicResources` to Agent, and set it on resource creation

### ISSUE THREAD

**Issue by pospi** [h-REA/hREA#133]
Spec additions to implement following https://github.com/valueflows/vf-graphql/pull/65 mean that `EconomicResource` now includes some logic about tracking "the agent currently with primary rights and responsibilites for the economic resource".

It is the agent that is associated with the accountingQuantity of the economic resource.

- [ ] on resource creation (actions: `produce`, `raise`) it can be set to the event `receiver` agent
- [ ] when there is a transfer or transfer-all-rights event, it (now the `toResourceInventoriedAs`, whether a new one or not) can be set to the receiver agent.
- [ ] new index on Agent

This scope of work should include the simple inverse queries on Agent class.
The inverse relationship is `inventoriedEconomicResources`

**Comment by Connoropolous** [comment]
@pospi I'm curious about this property, because I'd like to understand how we know which resources are associated with which agents. Is this implemented, I'm guessing not?

**Comment by pospi** [comment]
Not yet, it's actually a reasonably recent addition to the spec.

@fosterlynn can probably better answer your question of how agent -> resource association was done in the past; but presumably the need was covered by querying all `EconomicEvents` affecting the resource and locating the most recent one which involved an ownership change. Or possibly, it wasn't that important since most groups using VF tended to consider responsibilities as ending with their collective/s as a whole?

**Comment by fosterlynn** [comment]
>@fosterlynn can probably better answer your question of how agent -> resource association was done in the past; but presumably the need was covered by querying all EconomicEvents affecting the resource and locating the most recent one which involved an ownership change.

Not much to say besides what @pospi said.  You could do it by looking at those EconomicEvents, it is a derived field on EconomicResource.  But in software we've done, we kept it on EconomicResource.  We actually had a more involved structure in NRP, where you could define different roles between Agents and EconomicResources, one of which would be an "owner" role.  We haven't seen the need for that yet in VF.

Anyhow it is a handy field to have easily available, so we ended up putting it into VF in the simplest form, just for "ownership", or whatever ends up being like that in a new economy, for example some kind of primary responsibility or stewardship, if it is your land.  Or ownership if it is your toothbrush. :) 

So getting all resources with you as primaryAccountable gives you your inventory, accounts, etc.

**Comment by fosterlynn** [comment]
To add to the above explanation, and I see this is not totally clear in the VF spec, the following event actions should set the resource's `primaryAccountable` agent to the event's `receiver` agent.
* produce (the resource being created by the event, if there is one) [edited]
* transfer (`toResourceInventoriedAs` resource)
* transfer-all-rights (`toResourceInventoriedAs` resource)
* [edit] raise (if it is creating a new resource, otherwise not)

**Comment by Connoropolous** [comment]
thanks Lynn

**Comment by weswalla** [comment]
@Connoropolous @pospi do we need to add `EconomicResourceCreateParams` and `EconomicResourceUpdateParams` to https://lab.allmende.io/valueflows/vf-schemas/vf-graphql/-/blob/sprout/lib/schemas/bridging/agent.observation.gql

```
input EconomicResourceCreateParams {
  "The agent currently with primary rights and responsibilites for the economic resource. It is the agent that is associated with the accountingQuantity of the economic resource."
  primaryAccountable: ID
}

input EconomicResourceUpdateParams {
  "The agent currently with primary rights and responsibilites for the economic resource. It is the agent that is associated with the accountingQuantity of the economic resource."
  primaryAccountable: ID
}
```

**Comment by Connoropolous** [comment]
for the record, Wesley and I discussed this in a chat, and the answer being 'no'

**Comment by Connoropolous** [comment]
@fosterlynn is `raise` included in the set of actions that set `primaryAccountable`? Perhaps only if it uses `newInventoriedResource` instead of `resourceInventoriedAs`?

**Comment by fosterlynn** [comment]
>@fosterlynn is raise included in the set of actions that set primaryAccountable? Perhaps only if it uses newInventoriedResource instead of resourceInventoriedAs?

Absolutely right.  Thanks for the catch!  Yes, only if it is creating a new resource, otherwise not.  I edited the list above so it is in one place.

**Comment by pospi** [comment]
@fosterlynn what about `lower`? I do believe sometimes we initialise inventories with negative balances, maybe it should behave the same as `raise` for `newInventoriedResource`?
