### ISSUE TITLE
Add `onHandEffect` to `Action`

### ISSUE THREAD

**Issue by pospi** [h-REA/hREA#153]
Connor attempt at work plan:

- add `onhand_effect` next to `resource_effect` here:
https://github.com/h-REA/hREA/blob/588b017242acbe284dde00eee0e468ed24c922e3/lib/vf_actions/src/builtins.rs#L25
- based on **[this reference](https://www.valueflo.ws/concepts/actions/#action-behaviors)**, add an extra `ActionEffect` parameter to each line item here: https://github.com/h-REA/hREA/blob/588b017242acbe284dde00eee0e468ed24c922e3/lib/vf_actions/src/builtins.rs#L38-L55
- adjust `get_event_action` so that it incorporates this new `onhand_effect` value of the builtin actions, and uses it instead if appropriate https://github.com/h-REA/hREA/blob/588b017242acbe284dde00eee0e468ed24c922e3/zomes/rea_economic_resource/storage/src/lib.rs#L294-L298

background info:
See https://github.com/valueflows/vf-graphql/pull/81

**Comment by Connoropolous** [comment]
I am using this code
https://github.com/holo-rea/holo-rea/blob/57681b2aa84577fd95985e1d8fc4585c0361fc16/zomes/rea_economic_resource/storage/src/lib.rs#L300
as a signal that this work is implemented. Closing this issue, but if I'm wrong please re-open @pospi

**Comment by pospi** [comment]
Hmm, I think this is still yet to do. There should be new action metadata in `lib/vf_actions/src/builtins.rs` that gets picked up by the resource update methods. Still just has `resource_effect`.

The `update_quantity()` method of `EconomicResource` accepts the parameter as a hardcoded value, indicating *the field to be updated*. I believe there was some older logic for how `onhandQuantity` was updated which did not require this metadata in `Action`; and that new logic exists which involves some inference *on the definition of the `Action` itself*, rather than being achievable without.

@fosterlynn can confirm, and possibly point to the implementor pseudocode for how the new logic should behave?

**Comment by fosterlynn** [comment]
>The update_quantity() method of EconomicResource accepts the parameter as a hardcoded value, indicating the field to be updated.

Just a note that sometimes both are updated, don't know if you were limiting to one.  I just separated out the Action logic in the doc, it is here now https://www.valueflo.ws/concepts/actions/.

>I believe there was some older logic for how onhandQuantity was updated which did not require this metadata in Action; and that new logic exists which involves some inference on the definition of the Action itself, rather than being achievable without.@fosterlynn can confirm, and possibly point to the implementor pseudocode for how the new logic should behave?

I'm not quite understanding what you said about the history of the logic doc, but here is the most recent version of the suggested logic: https://lab.allmende.io/valueflows/valueflows/-/wikis/Application-specification-guidance#event-and-resource-logic.  And it does include the newest action metadata, not tested.  I see I still have some references to actions themselves, I should get rid of those if possible.  Will try to do that soon and report back, in case you want to make it all "data driven".  There also might be reference code in Reflow that @srfsh might be able to point you to, which is done very differently, by action.

**Comment by Connoropolous** [comment]
Ok I think I get the gist of it. Sounds like it should be an open issue, not a closed one.

**Comment by Connoropolous** [comment]
@pospi I think this might be up for getting done in MMR. I've updated the original description with what I think would be the work plan. Can you vet it when you get a chance? Not urgent.

**Comment by pospi** [comment]
That looks good, the method you've indicated is currently where the event math logic gets determined. But depending on how major these changes are to the internal logic of `EconomicEvent` & `EconomicResource` there may be a need to split that method out more to return separate data for handling both the `resourceInventoriedAs` and the `toResourceInventoriedAs` separately- I'm just not sure whether a single "`ActionInventoryEffect`" value can cover all cases now.

**Comment by Connoropolous** [comment]
Okay great. Noted

**Comment by Connoropolous** [comment]
Opened up the #357 linked PR for this. request your review @pospi  :)
