### ISSUE TITLE
Implement "read all" GraphQL query endpoints

### ISSUE THREAD

**Issue by pospi** [h-REA/hREA#84]
This will require changes to the `vf-graphql` spec, since none of these endpoints are parameterised yet. This also means thinking about the best way of doing pagination in distributed environments that is also compatible with traditional centralised systems.

See Column E here for [completions status](https://docs.google.com/spreadsheets/d/1bbp896cA6rc9A3OTCOfIn0DMYL-EoulXG2W90zG6oWw/edit#gid=0)

Most immediately:
- [x] #268 
- [x] #320 

Ongoing / later:
- [x] #222
- [ ] #85
- [x] #221
- [ ] #220

**Comment by pospi** [comment]
Updated resources on anchor pattern:

https://github.com/holochain/anchors
https://github.com/holochain/holochain_anchors

Examples:

https://github.com/holochain/anchors/blob/master/zomes/motorcycles
https://github.com/holochain/anchors/blob/master/zomes/motorcycles/code/Cargo.toml
https://github.com/holochain/anchors/blob/master/zomes/motorcycles/code/src/lib.rs

**Comment by pospi** [comment]
For an example of the super-basic version of this, see https://github.com/holo-rea/holo-rea/pull/129

**Comment by pospi** [comment]
Note that #85 should be finalised for `EconomicEvent` and `EconomicResource` before implementing the other endpoints, to avoid multiple refactorings / edits.

**Comment by pospi** [comment]
I think it's also worth rearchitecting this slightly in the process of finalising #85, before proceeding here.

There's redundant data split between zomes due to the "list all" API endpoints currently being present within the CRUD zomes. This results in `hdk_uuid_types` anchor entries being stored multiple times- once in the CRUD zome for "read all", and once in the indexing zomes for anchoring against other relationships. If we were to move the "read all" endpoints into the indexing zomes as well, the DHT data structures in the CRUD zomes would be much cleaner&mdash; they'd only need to store the actual entry data rather than link structures to point to them & allow iteration. The CRUD zome WASMs would also be quite a bit smaller because none of the indexing helpers would need to be compiled in.

**Comment by pospi** [comment]
> There's redundant data split between zomes due to the "list all" API endpoints currently being present within the CRUD zomes. This results in `hdk_uuid_types` anchor entries being stored multiple times[..]

These [concerns](https://github.com/h-REA/hREA/issues/84#issuecomment-1078743966) are addressed in #268.

**Comment by Connoropolous** [comment]
> This will require changes to the vf-graphql spec, since none of these endpoints are parameterised yet. This also means thinking about the best way of doing pagination in distributed environments that is also compatible with traditional centralised systems.

@pospi this is something I'd really like to get chatting about. 
I am not convinced even describing the system as "pagination"  is that useful, as there is no global ordering of records, therefore, how can you do 'pagination'. 

Eric HB has discussed this with me in the past, that what is useful is 'chunking', but I haven't reviewed the spec for that.

**Comment by pospi** [comment]
Yeah, chunking is how it's going to have to be implemented at the data layer. But we can create abstractions for that, and I think the mental model of "pages" is still pretty good as a "lowest common denominator" target. The algorithms are medium-difficulty, if a bit fiddly- you just need to iterate forwards / backwards in chunks until you retrieve up to your intended limits & discard the remainders; and iterate linearly when handling offsets. So if you're asking for the next page of 20 and there are 10 records stored on today's date & 15 tomorrow; then you're going to pull the first 10, want more, iterate forward in the DHT links structure, find the next 15, accumulate 10 more, discard the remaining 5 and return.

**Comment by pospi** [comment]
RE time ordering and sources of truth, this old discussion might be relevant- https://forum.holochain.org/t/mixin-zome-s-for-entry-timestamping/1307 And also relevant to note that I'm thinking about this ordering from the timestamp of the related `Element`'s header.
So, there are some APIs we could formalise around this timestamping stuff when we finish the list API work and get on to the metadata. For now I'm just going to be creating a linearly ordered index based on the associated `Element`'s header timestamp.

**Comment by Connoropolous** [comment]
I want to close this one now, we have issues that are more specialized:
#85 for pagination
#331 for ordered results for query_*
